services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    networks:
      - dev

  backend2:
    build:
      context: ./backend2
    networks:
      - dev

networks:
  dev:

